### ISSUE TITLE
I put in the correct query id but the tool still doesn't run. Why does it keep saying the wrong query id? Please fix it

### ISSUE THREAD

**Issue by daigia99xx** [adearman/tapswap#11]
![image](https://github.com/adearman/tapswap/assets/172129740/586bc80c-edf3-4643-9d96-56f5bd9f7670)

I put in the correct query id but the tool still doesn't run. Why does it keep saying the wrong query id? Please fix it

**Comment by B0ND07** [comment]
Fixed?
