### ISSUE TITLE
chr_value ada dimana bang?

### ISSUE THREAD

**Issue by 0xsiwant** [adearman/tapswap#2]
Chr value nyari ga nemu nemu bang

**Comment by adearman** [comment]
ga perlu chr lagi.

**Comment by indrabroh** [comment]
> ga perlu chr lagi.

terus isi init datanya cuma query id aja kah? tapi kok gini ya bang 
<img width="373" alt="image" src="https://github.com/adearman/tapswap/assets/169880504/423ee5b5-8b3c-40b2-828e-cb391bc3aa33">

**Comment by indrabroh** [comment]
<img width="122" alt="image" src="https://github.com/adearman/tapswap/assets/169880504/86dbae7b-f051-41de-89b9-238f6607464c">
isi init datanya gini kan?

**Comment by adearman** [comment]
lengkap dengan queryid=xxxx

Kalaiu pake v1 chr|query 
kalau pake v2 tanpa chr. langsung query

tapi v1 mati

**Comment by indrabroh** [comment]
<img width="380" alt="image" src="https://github.com/adearman/tapswap/assets/169880504/e56300d3-485e-4cfe-8298-0a42d54bde5c">
tetep aja gini bang pake tapv2

**Comment by adearman** [comment]
itu salah bang. query-idnya diikutin

**Comment by adearman** [comment]
CHECK UDAH KU UPDATE
