### ISSUE TITLE
Content time and id

### ISSUE THREAD

**Issue by cancinconntg** [adearman/tapswap#7]
Where can I find bro content time and content id?

**Comment by adearman** [comment]
when u tapping

**Comment by cancinconntg** [comment]
Bro can u write me in telegram
My telegram username @Cancincon

11 Haz 2024 Sal ÖÖ 4:59 tarihinde Ade Arman Wijaya ***@***.***>
şunu yazdı:

**Comment by adearman** [comment]
no need content
