### ISSUE TITLE
bot cannot execute

### ISSUE THREAD

**Issue by cyqdev** [adearman/tapswap#9]
![image](https://github.com/adearman/tapswap/assets/32971655/df6a58d7-94f5-44f6-9290-6ddd27d0737a)
It looks like you just updated your code, but it hava some bug

**Comment by cyqdev** [comment]
I have gotten the init_data parameter correctly

**Comment by toastyy00** [comment]
> ke you just updated your cod

i got same error, how do you fix it?

**Comment by adearman** [comment]
add your CHR before query
CHR|QUERY

chr got from payload

**Comment by toastyy00** [comment]
I can't find it, is it same with access token?
